apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: login
  namespace:  dev
spec:
  # 1 Pod should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: login
    spec:
      containers:
      - name: login
        # Run this image
        image: ravi2krishna/login-2428
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login
  namespace:  dev
spec:
  type: NodePort
  selector:
    app: login
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008