apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: ecomm
  namespace: qa
spec:
  # 1 Pod should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: ecomm
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: ecomm
    spec:
      containers:
      - name: ecomm
        # Run this image
        image: ravi2krishna/ecomm
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ecomm
  namespace: qa
spec:
  type: NodePort
  selector:
    app: ecomm
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009